In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [34]:
bankdata = pd.read_csv('data/bill_authentication.csv')

In [35]:
bankdata.head(20)

    Variance  Skewness  Curtosis  Entropy  Class
0    3.62160    8.6661  -2.80730 -0.44699      0
1    4.54590    8.1674  -2.45860 -1.46210      0
2    3.86600   -2.6383   1.92420  0.10645      0
3    3.45660    9.5228  -4.01120 -3.59440      0
4    0.32924   -4.4552   4.57180 -0.98880      0
5    4.36840    9.6718  -3.96060 -3.16250      0
6    3.59120    3.0129   0.72888  0.56421      0
7    2.09220   -6.8100   8.46360 -0.60216      0
8    3.20320    5.7588  -0.75345 -0.61251      0
9    1.53560    9.1772  -2.27180 -0.73535      0
10   1.22470    8.7779  -2.21350 -0.80647      0
11   3.98990   -2.7066   2.39460  0.86291      0
12   1.89930    7.6625   0.15394 -3.11080      0
13  -1.57680   10.8430   2.54620 -2.93620      0
14   3.40400    8.7261  -2.99150 -0.57242      0
15   4.67650   -3.3895   3.48960  1.47710      0
16   2.67190    3.0646   0.37158  0.58619      0
17   0.80355    2.8473   4.34390  0.60170      0
18   1.44790   -4.8794   8.34280 -2.10860      0
19   5.24230   11.0272  -4.35300 -4.10130      0

In [11]:
X = bankdata.drop('Class', axis=1)
y = bankdata['Class']

In [12]:
X

      Variance  Skewness  Curtosis  Entropy
0      3.62160   8.66610   -2.8073 -0.44699
1      4.54590   8.16740   -2.4586 -1.46210
2      3.86600  -2.63830    1.9242  0.10645
3      3.45660   9.52280   -4.0112 -3.59440
4      0.32924  -4.45520    4.5718 -0.98880
...        ...       ...       ...      ...
1367   0.40614   1.34920   -1.4501 -0.55949
1368  -1.38870  -4.87730    6.4774  0.34179
1369  -3.75030 -13.45860   17.5932 -2.77710
1370  -3.56370  -8.38270   12.3930 -1.28230
1371  -2.54190  -0.65804    2.6842  1.19520

[1372 rows x 4 columns]

In [13]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1367    1
1368    1
1369    1
1370    1
1371    1
Name: Class, Length: 1372, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [16]:
X_train.shape

(1097, 4)

In [17]:
X_test.shape

(275, 4)

In [18]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [19]:
y_pred = svclassifier.predict(X_test)
y_pred

array([1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0], dtype=int64)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[143   6]
 [  1 125]]
              precision    recall  f1-score   support

           0       0.99      0.96      0.98       149
           1       0.95      0.99      0.97       126

    accuracy                           0.97       275
   macro avg       0.97      0.98      0.97       275
weighted avg       0.98      0.97      0.97       275

In [37]:
bankdata['Predictions'] = pd.Series(y_pred)

In [40]:
bankdata.drop(columns='Class', inplace=True)

In [41]:
bankdata.head(30)

    Variance  Skewness  Curtosis  Entropy  Predictions
0    3.62160    8.6661  -2.80730 -0.44699          1.0
1    4.54590    8.1674  -2.45860 -1.46210          1.0
2    3.86600   -2.6383   1.92420  0.10645          0.0
3    3.45660    9.5228  -4.01120 -3.59440          1.0
4    0.32924   -4.4552   4.57180 -0.98880          0.0
5    4.36840    9.6718  -3.96060 -3.16250          0.0
6    3.59120    3.0129   0.72888  0.56421          1.0
7    2.09220   -6.8100   8.46360 -0.60216          1.0
8    3.20320    5.7588  -0.75345 -0.61251          1.0
9    1.53560    9.1772  -2.27180 -0.73535          0.0
10   1.22470    8.7779  -2.21350 -0.80647          0.0
11   3.98990   -2.7066   2.39460  0.86291          1.0
12   1.89930    7.6625   0.15394 -3.11080          0.0
13  -1.57680   10.8430   2.54620 -2.93620          1.0
14   3.40400    8.7261  -2.99150 -0.57242          0.0
15   4.67650   -3.3895   3.48960  1.47710          0.0
16   2.67190    3.0646   0.37158  0.58619          1.0
17   0.80355    2.8473   4.34390  0.60170          1.0
18   1.44790   -4.8794   8.34280 -2.10860          0.0
19   5.24230   11.0272  -4.35300 -4.10130          1.0
20   5.78670    7.8902  -2.61960 -0.48708          1.0
21   0.32920   -4.4552   4.57180 -0.98880          0.0
22   3.93620   10.1622  -3.82350 -4.01720          0.0
23   0.93584    8.8855  -1.68310 -1.65990          0.0
24   4.43380    9.8870  -4.67950 -3.74830          1.0
25   0.70570   -5.4981   8.33680 -2.87150          1.0
26   1.14320   -3.7413   5.57770 -0.63578          1.0
27  -0.38214    8.3909   2.16240 -3.74050          1.0
28   6.56330    9.8187  -4.41130 -3.22580          1.0
29   4.89060   -3.3584   3.42020  1.09050          1.0